### ISSUE TITLE
Allow insecure 

### ISSUE THREAD

**Issue by mysiki** [openstandia/connector-keycloak#15]
Hello,

you thinks it's possible to allow insecure connection ? Connection thought keycloak than the certificat is not trusted by truststore.

**Comment by netchild** [comment]
A connection to a https site fails if the CA of the cert is not in the trust store.

The trust store which is used is the java default keystore (according to https://docs.evolveum.com/midpoint/reference/support-4.8/security/crypto/keystore-configuration/ in the section "MidPoint Keystore and JVM Keystore" when configured like described and additionally the -Djavax.net.ssl.trustStorePassword=xxx java option is used in case the trust store password was changed).

In my case when I try to import the cert of the issuing CA (letsencrypt) as a trusted CA cert, it warns that the default certificate provider of java contains this already. Forcing keytool to import the cert (by answering "yes") results in a successful https connection. This is necessary, as the default certificate provider is not used when the default truststore is changed.

Importing your self-signed cert into the midpoint keystore (section Import Trusted CA Certificate at https://docs.evolveum.com/midpoint/reference/support-4.8/security/crypto/keystore-configuration/) should solve the issue you see.
